### ISSUE TITLE
The issue of array copy

### ISSUE THREAD

**Issue by tangdf** [ReubenBond/DeepCopy#19]
Demo Code:
```C#
            var originalArray = new string[] { "123", "hello!" };
            var resultArray = DeepCopier.Copy((object)original);
            Assert.Equal(originalArray, resultArray);
            Assert.NotSame(originalArray, resultArray);
```
Stace Trace:
> System.ArgumentException : Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type.
   at System.Reflection.RuntimeMethodInfo.CreateDelegateInternal(Type delegateType, Object firstArgument, DelegateBindingFlags bindingFlags, StackCrawlMark& stackMark)
   at System.Reflection.RuntimeMethodInfo.CreateDelegate(Type delegateType)
   at DeepCopy.CopierGenerator`1.CreateArrayCopier(Type type) 
   at DeepCopy.CopierGenerator`1.CreateCopier(Type type) 
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at DeepCopy.CopierGenerator`1.Copy(T original, CopyContext context) 
   at DeepCopy.DeepCopier.Copy[T](T original) 
   at DeepCopy.UnitTests.CopyTests.CanCopyArrays()

**Comment by alirezapla** [comment]
If you want to continue using DeepCopier, ensure that you are calling it correctly

```c#
var originalArray = new string[] { "123", "hello!" };
var resultArray = DeepCopier.Copy(originalArray); // Ensure you're passing the correct type
```
