### ISSUE TITLE
Not Support HashSet<>,Dictionary<>

### ISSUE THREAD

**Issue by tangdf** [ReubenBond/DeepCopy#8]
```csharp
        [Fact]
        public void CopyHashSet()
        {
            HashSet<string> original = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

            original.Add("A");
            original.Add("B");

            var result = DeepCopier.Copy(original);

            Assert.NotSame(original, result);
            Assert.True(result.Contains("b"));
            Assert.True(result.Contains("a"));

        }
```
> System.TypeInitializationException : The type initializer for 'DeepCopy.CopierGenerator`1' threw an exception.
---- System.NotSupportedException : Illegal one-byte branch at position: 10. Requested branch was: 136.
   at DeepCopy.CopierGenerator`1.Copy(T original, CopyContext context) in G:\source\DeepCopy-master\DeepCopy-master\src\DeepCopy\CopierGenerator.cs:line 26
   at DeepCopy.DeepCopier.Copy[T](T original) in G:\source\DeepCopy-master\DeepCopy-master\src\DeepCopy\DeepCopier.cs:line 26
   at DeepCopy.UnitTests.CopyTests.CopyHashSet() in G:\source\DeepCopy-master\DeepCopy-master\test\DeepCopy.UnitTests\CopyTests.cs:line 170
----- Inner Stack Trace -----
   at System.Reflection.Emit.ILGenerator.BakeByteArray()
   at System.Reflection.Emit.DynamicResolver..ctor(DynamicILGenerator ilGenerator)
   at System.Reflection.Emit.DynamicILGenerator.GetCallableMethod(RuntimeModule module, DynamicMethod dm)
   at System.Reflection.Emit.DynamicMethod.GetMethodDescriptor()
   at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType)
   at DeepCopy.CopierGenerator`1.CreateCopier(Type type) in G:\source\DeepCopy-master\DeepCopy-master\src\DeepCopy\CopierGenerator.cs:line 150
   at DeepCopy.CopierGenerator`1..cctor() in G:\source\DeepCopy-master\DeepCopy-master\src\DeepCopy\CopierGenerator.cs:line 17

**Comment by tangdf** [comment]
https://github.com/ReubenBond/DeepCopy/blob/e2789c5b98f60a1e112b01bcfab0f806aea6e122/src/DeepCopy/CopierGenerator.cs#L68-L73

Change `OpCodes.Brtrue_S` to `OpCodes.Brtrue`.

**Comment by ReubenBond** [comment]
@tangdf good find. I thought that might come back to bite me eventually :)

**Comment by ReubenBond** [comment]
This particular issue is fixed, but there's still the separate issue you reported of collections which use reference equality
